item1 = input("Order your first favourite food ")
item2 = input("Order your second favourite food ")
item3 = input("Order your third favourite food ")
print("Order confirmed. You have ordered:")
print(item1)
print(item2)
print(item3)